name: Ruby

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.7.4']

    steps:
    - uses: actions/checkout@v2
    - name: Setup Ruby, JRuby and TruffleRuby
      # You may pin to the exact commit or the version.
      # uses: ruby/setup-ruby@57d46d78b7d959dc4a248024a29bb17d4e357e5c
      uses: ruby/setup-ruby@v1.81.0
      with:
        # Engine and version to use, see the syntax in the README. Reads from .ruby-version or .tool-versions if unset.
        ruby-version: 2.7.4 # optional, default is default
        # The version of Bundler to install. Either 'none', 'latest', 'Gemfile.lock', or a version number (e.g., 1, 2, 2.1.4). For 'Gemfile.lock', the version is determined based on the BUNDLED WITH section from the file Gemfile.lock, $BUNDLE_GEMFILE.lock or gems.locked. Defaults to 'Gemfile.lock' if the file exists and 'latest' otherwise.

        bundler: # optional, default is default
        # Run "bundle install", and cache the result automatically. Either true or false.
        bundler-cache: # optional, default is false
        # The working directory to use for resolving paths for .ruby-version, .tool-versions and Gemfile.lock.
        working-directory: # optional, default is .
        # Arbitrary string that will be added to the cache key of the bundler cache. Set or change it if you need to invalidate the cache.

        cache-version: # optional, default is 0
    - name: Rubocop checks
      # You may pin to the exact commit or the version.
      # uses: gimenete/rubocop-action@649c2b18b5726302b6b120dad74c25d2b2f391e9
      uses: gimenete/rubocop-action@1.0
